# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DailyReminder' do

  # Pods for DailyReminder
  pod 'SpacedRepetition', path: '../../git/SpacedRepetition/'
end
